
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: c_redis
    networks:
      - backend_net
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
      - "8001:8001"
  my-app:
    image: rascal98/redis-app-image
    container_name: c_redis_app
    ports:
      - "8080:8080"
    networks:
      - backend_net
networks:
  backend_net:
   name: backend_net
   external: true