
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: c_redis
    hostname: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
  my-app:
    image: redis-app-image
    container_name: c_redis_app
    depends_on:
      - redis-stack
    links:
      - redis-stack:redis-stack
    ports:
      - "8080:8080"