name: Umut Github Acions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up .Net Core
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x
            - name: Install dependencies
              run: dotnet restore  
            - name: Build
              run: dotnet build --configuration Release --no-restore
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up .Net Core
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 8.0.x
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/redis-app-image:latest, ${{ secrets.DOCKERHUB_USERNAME }}/redis-app-image:${{ github.run_number }}